"""level table

Revision ID: 32705cd66947
Revises: 00f847c47ca1
Create Date: 2019-05-26 11:31:10.356913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32705cd66947'
down_revision = '00f847c47ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('levelname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_level_levelname'), 'user_level', ['levelname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_level_levelname'), table_name='user_level')
    op.drop_table('user_level')
    # ### end Alembic commands ###
