"""level relations v2

Revision ID: ac2ab56ff660
Revises: b62faa6680a3
Create Date: 2019-05-26 11:59:08.479981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac2ab56ff660'
down_revision = 'b62faa6680a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_level', ['level_id'], ['id'])
    op.drop_column('user', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'user_level', ['level'], ['id'])
    op.drop_column('user', 'level_id')
    # ### end Alembic commands ###
